visualize: True
build_gps: True
visual_scale: 15
front_lidar_x: 0.0
front_lidar_y: 0.0
front_lidar_z: 0.0
rear_lidar_x: 0.0
rear_lidar_y: 0.0
rear_lidar_z: 0.0
filter_leaf_size: 0.2
segmentation_threshould: 0.5
cluster_tolerance: 0.3
min_cluster_size: 5
max_cluster_size: 10000
